function Y = params()
    Y.Subfolders={ ...
    'H','Nature/HistMatch0';'I','Nature/HistMatch10';'J','Nature/HistMatch20';'K','Nature/HistMatch30';'L','Nature/HistMatch40';...
    'Q','Texture/HistMatch0';'R','Texture/HistMatch10';'S','Texture/HistMatch20';'T','Texture/HistMatch30';'U','Texture/HistMatch40'
    };
end
